[[location]]
label = "demo"
token = "demo-token"
path = "./demo"
# path = "/home/sniner/Downloads"
allow_recurse = true
allow_write = true
allow_create = true
allow_replace = true
allow_delete = true

[[location]]
label = "open"
path = "./demo"
allow_recurse = true
allow_write = true
allow_create = true
allow_replace = true

[[location]]
label = "flat"
path = "./demo"
allow_recurse = false
